# Generated by Django 3.1 on 2020-08-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('ref_user', models.CharField(max_length=200)),
                ('ref_user_code', models.CharField(max_length=200)),
            ],
        ),
    ]
